### ISSUE TITLE
expert datasets

### ISSUE THREAD

**Issue by chenmao001** [Div99/IQ-Learn#1]
When I use trajectory in iq_learn/experts/, the results are not optimal. Are these just demo datas?  It seems that expert datasets from Dropbox cannot be downloaded successfully.
Thanks for your help!

**Comment by Div-Infinity** [comment]
Hi chenmao001, thanks for raising the issue. The `experts` directory contains the expert demonstrations generated using a trained RL agent. Their performance should be the same as the expert performance reported in the paper. 

I will make a fix to the Dropbox over the weekend and post an update soon.

**Comment by Div-Infinity** [comment]
Update: All the expert_data for Mujoco and Gym Box environments is available in the repo. The expert_data for Atari envs exceeds 5GB making it hard to store with Github.

 The current DropBox link containing the data seems to have expired. I will post Google Drive links to download the Atari Expert Data.

**Comment by shuoye1000** [comment]
> Update: All the expert_data for Mujoco and Gym Box environments is available in the repo. The expert_data for Atari envs exceeds 5GB making it hard to store with Github.
> 
> The current DropBox link containing the data seems to have expired. I will post Google Drive links to download the Atari Expert Data.Hello, could you please provide breakout and space? It seems that such datasets can be made very small after compression, so perhaps they can be uploaded to github without problems.

**Comment by shuoye1000** [comment]
> Hi chenmao001, thanks for raising the issue. The `experts` directory contains the expert demonstrations generated using a trained RL agent. Their performance should be the same as the expert performance reported in the paper.
> 
> I will make a fix to the Dropbox over the weekend and post an update soon.

Hello, could you please provide breakout and space? It seems that such datasets can be made very small after compression, so perhaps they can be uploaded to github without problems.

**Comment by Div-Infinity** [comment]
Hi sorry for the delay, I fixed the link to the Atari datasets in the repo and they can be downloaded from Google Drive. 

Best,
Div
