### ISSUE TITLE
Getting missing args error running train_iq.py examples from run_offline.sh

### ISSUE THREAD

**Issue by R-Liebert** [Div99/IQ-Learn#10]
Hi!

I've been trying to get some of the examples going, but I keep getting a issue with initating the models. The error belowe is from running the CartPole_v1 from the run_offline.sh.

Error in call to target 'agent.softq_models.OfflineQNetwork':
TypeError("__init__() missing 1 required positional argument: 'args'")
full_key: q_net.args.agent.critic_cfg

As I get the same error trying several models and env I assume it's something I've overlooked. I'm not getting any errors about dependecies.

**Comment by Div-Infinity** [comment]
Seems like a hydra version issue, please use `hydra-core=1.0`

**Comment by R-Liebert** [comment]
You are absolutly right! Thank you for the pointer.
